#ifndef KEYBOARD_H
#define KEYBOARD_H

#include <SDL2/SDL.h>

enum OS_KEYBOARD_TYPE
{
	QUIT = SDL_QUIT,
	KEY_DOWN = SDL_KEYDOWN,
};

enum OS_KEYBOARD_KEY {
	BT_ARROW_LEFT = SDLK_LEFT,
	BT_ARROW_RIGHT = SDLK_RIGHT,
	BT_ARROW_UP = SDLK_UP,
	BT_ARROW_DOWN = SDLK_DOWN,
	BT_KEY_P = SDLK_p,
};

#endif // !KEYBOARD_H
