#ifndef MOUSE_H
#define MOUSE_H

#include <SDL.h>

enum OS_MOUSE_STATE {
	MOUSE_DOWN = 1,
	MOUSE_RELEASE = 2,
};

enum OS_MOUSE_TYPE {
	MOTION = SDL_MOUSEMOTION,
	BUTTON_DOWN = SDL_MOUSEBUTTONDOWN,
	BUTTON_UP = SDL_MOUSEBUTTONUP
};

enum OS_MOUSE_BUTTON {
	BUTTON_LEFT = SDL_BUTTON_LEFT,
	BUTTON_RIGHT = SDL_BUTTON_RIGHT,
};


#endif // !MOUSE_H
